spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:bp_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    thymeleaf:
        cache: false